### PR TITLE
Bug fix v4

### LINKED ISSUE #203: [PE-D][Tester D] Error message does not correctly display optional field "Other Number"
The error message from this makes it seem like "other number", on, is a mandatory field to include when adding a contact, since its not bracketed, but it is actually an optional field, like how tag is an optional field. 

Image

Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #217: [PE-D][Tester C] Functionality bug: Unclear error message when trying to have two of the same phone number in the address book
Image

- Error message may not be clear enough for users to understand what is wrong with their input.
- User Guide does not mention that every person has a unique phone number.

**SUGGESTION**
- I think it can be improved by changing the error message to `Phone number already exists in the address book.`
- User Guide can also include that phone number is unique, whereas other attributes may not be unique.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #222: [PE-D][Tester A] Duplicate Detection Unclear
Based on the GUI, people are identified uniquely based purely on their phone number, however, assuming Person A has their main number 98765432, Person B can have their Main Number as 12345678 and their ON(other number) as also 98765432. Not sure if this is the intended behavior. (Can refer to the screenshot below where Jane Smith's Other Number is John's Main Number)

Putting this as a documentation flaw since the User Guide has no mention of how duplicates are determined and what uniquely identifies a Person. Would be good to add this in the User Guide to resolve any ambiguity or identify a Person by their name and phone number.

Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #237: [PE-D][Tester A] Misleading Exception Message for Phone Number
When invalid phone numbers input is given, the following error message thrown specifies that phone numbers should only contain numbers and must be at least 3 digit long

Image

However, this is not accurate as certain special characters are allowed such as `+` and the alphabet `x` as seen in the screenshot below which can be reproduced with a  `add n= Peter Parker mn= +65 87638918 e=test@example.com a=Jurong West` or replace the `mn` field with `123 x456`

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #240: [PE-D][Tester B] Error message not specific
Image
In the diagram above, when a user attempts to add tags to the main phone number, the error message “Phone number should only contain numbers” appears.

While this message is technically correct, its specificity could be improved. It is quite natural for users to try tagging the main phone number, and in such cases, the current message can be misleading. Since the phrase “phone number” is currently used in a general sense that could refer to both mn and on, users may wrongly assume that any format valid for on should also work for mn. Refining the message would make the feedback clearer and more user-friendly.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #253: [PE-D][Tester D] Phone number field has no limit
## Issue
The phone number field has no limit to how long it can be. Meanwhile a field like the name field has a limit of 95 characters to it.

Image

Image

## Suggestion 
You might want to consider limiting it to 17 numbers (longest phone number in the world by country) or even limiting it to 8 numbers in Singapore's context.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #254: [PE-D][Tester C] Functionality bug: Incorrect success message with missing parameters for edit function
Image

- Success message of `edit` command does not show correct output.
- Input: `edit 3 on=98765432` .
- Output: Contact is updated but feedback box does not include the OTHER_NUMBER as the output message.

**SUGGESTION**
- Update success message to include edited parameters, such that it matches with the output.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by nicsohlame**
Resolves #254 , Resolves #253, Resolves #240, Resolves #237, Resolves #222, Resolves #217, Resolves #203

Fixes: 
- Error message of other number to be optional
- Update UG to specify unique phone number 
- Update error message to specify that main number already exists in the address book
- Update UG to specify that other number can contain other contacts main number except the main number of the added user
- Exception message for phone number is more detailed.
- Limit the character length of phone number to 25.
- Update success message to contain other number parameters for edit function

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PhoneTest.java [hunk 1]
```diff
@@ -31,11 +31,16 @@ public void isValidPhone() {
...
+        assertFalse(Phone.isValidPhone("+65 999999999999999999999 x1"));
 
         // valid phone numbers
         assertTrue(Phone.isValidPhone("911")); // exactly 3 numbers
         assertTrue(Phone.isValidPhone("93121534"));
-        assertTrue(Phone.isValidPhone("124293842033123")); // long phone numbers
+        assertTrue(Phone.isValidPhone("124293842033123"));
+        // 25 digits (maximum length)
+        assertTrue(Phone.isValidPhone("1242938420331231111111111"));
     }
```
Comment (Zisaac99) [inline src/test/java/seedu/address/model/person/PhoneTest.java]: Should we add one more for 25 digits with country code and extensions?
